CC=g++
FLAGS=-c -Wall -O2 -g -std=c++11

all:
	$(CC) $(FLAGS) registerServer.cpp -o ../test/registerServer.o
	$(CC) $(FLAGS) registerClient.cpp -o ../test/registerClient.o
	$(CC) $(FLAGS) WriteToDataBase.cpp -o ../test/WriteToDataBase.o
