CC=g++
FLAGS=-c -Wall -O2 -g -std=c++11

all:
	$(CC) $(FLAGS) dnsClient.cpp -o ../test/dnsClient.o
	$(CC) $(FLAGS) dnsService.cpp -o ../test/dnsService.o
	$(CC) $(FLAGS) DnsRoute.cpp -o ../test/DnsRoute.o
	$(CC) $(FLAGS) Subscribe.cpp -o ../test/Subscribe.o
