CC=g++
FLAGS=-c -Wall -O2 -g -std=c++11

all:
	$(CC) $(FLAGS) reportClient.cpp -o ../test/reportClient.o
	$(CC) $(FLAGS) reportService.cpp -o ../test/reportService.o
	$(CC) $(FLAGS) StoreReport.cpp -o ../test/StoreReport.o
