CC=g++
FLAGS=-c -Wall -O2 -g -std=c++11

all:
	$(CC) $(FLAGS) ./IOBuff/IObuf.cpp -o ../test/IObuf.o
	$(CC) $(FLAGS) ./IOBuff/ReactorBuff.cpp -o ../test/ReactorBuff.o
	$(CC) $(FLAGS) ./IOBuff/OutputBuff.cpp -o ../test/OutputBuff.o
	$(CC) $(FLAGS) ./IOBuff/BuffPool.cpp -o ../test/BuffPool.o
	$(CC) $(FLAGS) ./IOBuff/InputBuff.cpp -o ../test/InputBuff.o
	$(CC) $(FLAGS) ./example/server.cpp -o ../test/server.o
	$(CC) $(FLAGS) ./example/userver.cpp -o ../test/userver.o
	$(CC) $(FLAGS) ./example/client.cpp -o ../test/client.o
	$(CC) $(FLAGS) ./example/uclient.cpp -o ../test/uclient.o
	$(CC) $(FLAGS) ./net/TcpClient.cpp -o ../test/TcpClient.o
	$(CC) $(FLAGS) ./net/UdpServer.cpp -o ../test/UdpServer.o
	$(CC) $(FLAGS) ./net/TcpServer.cpp -o ../test/TcpServer.o
	$(CC) $(FLAGS) ./net/UdpClient.cpp -o ../test/UdpClient.o
	$(CC) $(FLAGS) ./net/ThreadPool.cpp -o ../test/ThreadPool.o
	$(CC) $(FLAGS) ./net/EventLoop.cpp -o ../test/EventLoop.o
	$(CC) $(FLAGS) ./net/TcpConnection.cpp -o ../test/TcpConnection.o
	





